Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('accounts/',include('registration.backends.default.urls')),
    path('paypal/', include("paypal.standard.ipn.urls")),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    

login/app/urls.py
from django.urls import path
from app.views import homepage,login,registration
app_name='app'
urlpatterns = [
    path('',login,name='login'),
    path('reg/',registration,name='registration'),
    path('home/',homepage,name='homepage')
    path('otp/<str:otp>/<str:password>/<str:email>/',otp,name='otp')
]

login/login/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls'))
]

myapp/urls.py
from django.contrib import admin
from django.urls import path,include
from myapp.views import   send_email,order, products, detail, cart_view, return_view, add_reply, cancel_view,add_review,contact_us,contact_us_success,category,faq_list
app_name='myapp'

urlpatterns = [
    path('category/', category, name='myapp:category'),
    path('',category,name='category'),
    path('products/<int:product_id>/<slug:slug>',products,name='products'), 
    path('<int:product_id>/<slug:slug>',detail,name='detail'), 
    path('cart/',cart_view,name='cart_view'),
    path('order/',order,name='order'),
    path('success/',return_view,name='return_view'),
    path('cancel/',cancel_view,name='cancel_view'),
    path('sendmail/',send_email,name="send_email"),
    # Assuming 'add_reply' is the URL endpoint for adding replies
    path('product/<int:product_id>/add_review/', add_review, name='add_review'),
    #path('otp/<str:otp>/<str:password>/<str:email>/',otp,name='otp'),
    path('contact/', contact_us, name='contact_us'),  # Define the URL pattern for contact_us
    path('contact/success/', contact_us_success, name='contact_us_success'),  # Success page after submitting contact form
    path('faqs/', faq_list, name='faq_list'),
]

myapp/models.py
from django.contrib.auth.models import User
from django.db import models

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
class Category(models.Model):
    title=models.CharField(max_length=50)
    img=models.ImageField(upload_to='')
    slug=models.SlugField()
    def __str__(self):
        return self.title
class Product(models.Model):
    title=models.CharField(max_length=100)
    description=models.TextField()
    slug=models.SlugField()
    price=models.DecimalField(max_digits=10,decimal_places=2)
    img=models.ImageField(upload_to='')
    product_avaliable = models.BooleanField(default=False)
    category = models.ForeignKey(Category,on_delete=models.CASCADE,default=1)
    
    def __str__(self):
        return self.title
class Cart(models.Model):
    cart_id=models.CharField(max_length=100)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    quantity=models.IntegerField()
    timestamp=models.DateTimeField(auto_now=True)
    product=models.ForeignKey(Product,on_delete=models.PROTECT)

    def __str__(self):
        return self.product.title
    def update_quantity(self,quantity):
        self.quantity+=quantity
        self.save()
    def total(self):
        return self.quantity*self.price
class Buy(models.Model):
    product=models.ForeignKey(Product,on_delete=models.PROTECT)
    quantity=models.IntegerField()
    price=models.DecimalField(max_digits=10,decimal_places=2)

    def __str__(self):
        return self.product.title+'_'+str(self.id)
class Reply(models.Model):      
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='replies')

    def __str__(self):
        return f"Reply by {self.user.username} on {self.product.title}"
class ContactMessage(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message from {self.name} - {self.subject}"
class FAQ(models.Model):
    question = models.CharField(max_length=255)
    answer = models.TextField()

myapp/forms.py
from django import forms

class CartForm(forms.Form):
    quantity=forms.IntegerField(initial='1')
    product_id=forms.IntegerField(widget=forms.HiddenInput)

    def __init__(self,request,*args,**kwargs):
        self.request=request
        super(CartForm,self).__init__(*args,**kwargs)
from .models import ContactMessage

class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name', 'email', 'subject', 'message']

myapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from myapp.models import Product,Cart,Buy,Reply,Category,FAQ
from myapp.forms import CartForm
from myapp.myapp import *
from django.urls import reverse
from django.shortcuts import render
from paypal.standard.forms import PayPalPaymentsForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, get_object_or_404
from .models import ContactMessage
from .forms import ContactForm
# Create your views here.
def category(request):
    c = Category.objects.all()
    p = None  # Initialize p with a default value
    if request.GET.get('q'):
        query = request.GET.get('q')
        p = Product.objects.filter(title__contains=query)
    context = {'c': c, 'p':p}
    return render(request, 'index.html', context)

def products(request,product_id,slug):
    p=Product.objects.filter(category=product_id)
    if request.GET.get('q'):
        query=request.GET.get('q')
        p=Product.objects.filter(title__contains=query)
    context={'p':p}
    return render(request,'index.html',context)
    
def detail(request,product_id,slug):
    d=Product.objects.get(id=product_id)
    reviews =Reply.objects.filter(product=d)
    if request.method=="POST":
        f=CartForm(request,request.POST)
        if f.is_valid():
            request.form_data=f.cleaned_data
            add_to_cart(request)
            return redirect('myapp:cart_view')
    f=CartForm(request,initial={'product_id':product_id})
    context={'d':d,'f':f,'reviews': reviews}
    return render(request,'detail.html',context)
def cart_view(request):
    if request.method=="POST" and request.POST.get('delete')=='Delete':
        item_id=request.POST.get('item_id')
        cd=Cart.objects.get(id=item_id)
        cd.delete( )
    c=get_cart(request)
    t=total_(request)
    co=item_count(request)
    context={'c':c,'t':t}
    return render(request,'cart.html',context)
def order(request):
    # What you want the button to do.
    items=get_cart(request)
    for i in items:
        b=Buy(product_id=i.product_id,quantity=i.quantity,price=i.price)
        b.save()
    paypal_dict = {
        "business": "sb-l7r2e28145955@business.example.com",
        "amount": total_(request),
        "item_name":cart_id(request),
        "invoice": str(uuid.uuid4()),
        "notify_url": request.build_absolute_uri(reverse('paypal-ipn')),
        "return": request.build_absolute_uri(reverse('myapp:return_view')),
        "cancel_return": request.build_absolute_uri(reverse('myapp:cancel_view')),
        "custom": "premium_plan",  # Custom command to correlate to some function later (optional)
    }

    # Create the instance.
    form = PayPalPaymentsForm(initial=paypal_dict)
    context = {"form": form,"items":items,"total":total_(request)}
    return render(request, "order.html", context)
def return_view(request):
    return HttpResponse('Transaction Succesful')
def cancel_view(request):
    return HttpResponse('Transaction Cancelled')
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse, HttpResponseRedirect


def send_email(request):
    subject = request.POST.get("subject", "Hi Geld Bro")
    message = request.POST.get("message", "otp is 465625")
    from_email = request.POST.get("from_email", "chaitanya4656@gmail.com")
    if subject and message and from_email:
        try:
            send_mail(subject, message, from_email, ["admin@example.com"])
        except BadHeaderError:
            return HttpResponse("Invalid header found.")
        return HttpResponseRedirect("Mail sent to geld")
    else:
        # In reality we'd use a form class
        # to get proper validation errors.
        return HttpResponse("Make sure all fields are entered and valid.")
def add_reply(request, product_id):
    if request.method == "POST" and request.user.is_authenticated:
        reply_text = request.POST.get('reply_text')
        product = get_object_or_404(Product, id=product_id)
        
        if reply_text:
            ProductReply.objects.create(product=product, user=request.user, reply_text=reply_text)
            # Redirect back to the product detail page after adding the reply
            return redirect('myapp:detail', product_id=product_id, slug=product.slug)
    
    # Redirect to a specific page if there's an issue with adding the reply
    return redirect('myapp:some_error_page')

#===========================================================================rating and reviews code
'''def add_rating(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if request.method == 'POST':
        rating_value = request.POST.get('rating_value')
        if rating_value:
            user = request.user
            rating, created = Rating.objects.get_or_create(user=user, product=product)
            rating.rating = int(rating_value)
            rating.save()
            # Perform any other actions you need after adding a rating
    return HttpResponseRedirect(product.get_absolute_url())'''
def add_review(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if request.method == 'POST':
        review_content = request.POST.get('review_content')
        if review_content:
            user = request.user
            review = Reply.objects.create(user=user, content=review_content, product=product)
            # Perform any other actions you need after adding a review
            # Redirect to the product detail view after adding the review
            review.save()
            return redirect('myapp:detail', product_id=product.id, slug=product.slug)
    
    # If there's an issue adding the review, redirect to a specific page
    return HttpResponseRedirect(reverse('myapp:index'))
    
    # If there's an issue adding the review, redirect to a specific page
    return HttpResponseRedirect(reverse('myapp:index'))


#=============================== contact us

def contact_us(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('myapp:contact_us_success')  # Redirect to a success page after form submission
    else:
        form = ContactForm()
    return render(request, 'contact_us.html', {'form': form})

def contact_us_success(request):
    return render(request, 'contact_us_sucess.html')
def category_detail(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    
    # Filter products for the selected category, including products without a category
    products_in_category = Product.objects.filter(categories__in=[category, None])

    context = {'category': category, 'products': products_in_category}
    return render(request, 'category_detail.html', context)
def faq_list(request):
    faqs = FAQ.objects.all()
    return render(request, 'faq_list.html', {'faqs': faqs})

myapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, 
    initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</head>
<style>
  body{
    background-image: url('');
    background-size: cover;
  }
</style>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-warning">
    <a class="navbar-brand" href="#">Ecommerce</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'myapp:faq_list' %}">FAQ</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'myapp:contact_us' %}">Contact us</a>
          </li>
          </ul>
          <form class="form-inline my-2 my-lg-0" >
            <input class="form-control mr-sm-2" type="search" name="q" value="{{ request.GET.q }}" placeholder="Search" aria-label="Search">
        </form>
          {% if not user.is_authenticated %}
             <a class="btn btn-primary" href="{% url 'auth_login' %}" >Login</a>&nbsp;
        
            <a class="btn btn-primary" href="{% url 'registration_register' %}">Register</a>   
          {% else %}
          <a href="{% url 'myapp:cart_view' %}"class="btn btn-outline-success my-2 my-sm-0">Cart</a>
          <a class="btn btn-primary" href="{% url 'auth_logout' %}">Logout</a>
          {% endif %}
        </div>
      </nav>
      <center><h1>WELCOME TO ECOMMERCE </h1></center>
  <div class="container">
    <br>
{% block content %}

{% endblock %}
<footer class="bg-dark text-light py-3">
      <div class="container text-center">
          <p>&copy; 2023 Ecommerce Store. All Rights Reserved.</p>
</div>
</body>
</html>

myapp/templates/cart.html
{% extends 'base.html' %}
{% block content %}
<table class="table table-info">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Product</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Total Cost</th>
      </tr>
    </thead>
    <tbody>
        {% for i in c %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{i.product}}</td>
        <td>{{i.price}}</td>
        <td>{{i.quantity}}</td>
        <td>{{i.total}}</td>
        <td>
        <form action="" method="POST">
            {% csrf_token %}
            <input type="hidden" name="item_id" value="{{i.id}}">
            <input class="btn btn-danger" type="submit" name="delete" value="Delete">
        </form>
   </td>
      </tr>
      {% endfor %}
    </tbody>
  </table><br>
  Total: ₹{{t}}<br>
  <br>
  <a class="btn btn-info" href="{% url 'myapp:order' %}">Order</a>
  &nbsp;&nbsp;&nbsp;
  <a class="btn btn-info" href="{% url 'myapp:category' %}">Back/Continue</a>
{% endblock %}

myapp/templates/categories.html
{% extends 'base.html' %}

{% block content %}

<style>
    body {
        font-family: 'YourStylishFont', sans-serif; /* Replace 'YourStylishFont' with the desired font */
    }

    .card {
        border-radius: 15px;
        overflow: hidden;
    }

    .category-heading {
        font-family: 'YourStylishFont', sans-serif; /* Apply the stylish font to the category heading */
        font-size: 24px;
        font-weight: bold;
        margin-top: 20px;
        white-space: nowrap;
        overflow: hidden;
        box-sizing: border-box;
        animation: marquee 15s linear infinite;
    }

    .col-md-2 {
        flex: 0 0 calc(20% - 10px); /* Adjust width and margin as needed */
        margin: 0 5px 20px 5px; /* Adjust margin as needed */
    }

    .card-container {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
    }

    @keyframes marquee {
        0% { transform: translateX(100%); }
        100% { transform: translateX(-100%); }
    }
</style>
<div class="container">
    <!-- Marquee for Categories -->
    <div class="category-heading marquee" style="font-family: 'YourStylishFont', sans-serif;">
        <span><b><h1  style="color: rgba(0, 187, 255, 0.949)">CATEGORIES</h1></b></span><br><br>
        <!-- Add more categories as needed -->
    </div>
    <div class="card-container">
        {% for i in c %}
            <div class="col-md-2">
                <div class="card">
                    <a href="{% url 'myapp:products' i.id i.slug %}">
                        <img src="{{i.img.url}}" class="card-img-top" alt="{{i.title}}" width="100%" height="200px">
                    </a>
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="{% url 'myapp:products' i.id i.slug %}">{{i.title}}</a>
                        </h5>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

myapp/templates/contact_us.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    {% endblock %}

myapp/templates/contact_us_success.html
{% extends 'base.html' %}
{% block content %}
    <h2>Thank you for your message!</h2>
<p>We will get back to you soon.</p>
{% endblock %}

myapp/templates/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
<div class="row">
<div class="col-md-6">
    <br>{{d.title}}
    {{d.description}}<br>
    Price:  ₹{{d.price}}<br>
    </div>
    <div class="col-md-6">
        <img src="{{d.img.url}}" width="400", height="400" alt="{{d.title}}">
    </div>
</div>

<div class="mt-4">
    <div class="row">
        <div class="col-md-6">
            {% if d.product_avaliable and user.is_authenticated %}
            <form action="{% url 'myapp:detail' d.id d.slug %}" method="post">
                {% csrf_token %}
                {{ f }}
                <input type="submit" value="Add to Cart" class="btn btn-primary">
            </form>
            {% else %}
                <p class="card-text text-danger">Out of Stock</p>
              {% endif %}
        </div>
        
    </div>
</div>


{% if user.is_authenticated %}
<div class="mt-4">
    <form method="post" action="{% url 'myapp:add_review' d.id %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="review_content">Add a Review</label>
            <textarea class="form-control" id="review_content" name="review_content" rows="4" placeholder="Write your review here"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit Review</button>
    </form>
</div>
{% else %}
<div class="mt-4">
    <p>Please <a href="{% url 'auth_login' %}">login</a> to add a review or rating.</p>
</div>
{% endif %}

<hr>

{% if reviews %}
<div class="mt-4">
    <h2>Reviews</h2>
    <ul class="list-group">
        {% for review in reviews %}
        <li class="list-group-item">
            <p>{{ review.content }}</p>
            <small class="text-muted">Date: {{ review.timestamp|date:"F d, Y" }}</small>
        </li>
        {% endfor %}
    </ul>
</div>
{% else %}
<div class="mt-4">
    <p>No reviews yet.</p>
</div>
{% endif %}
</div>
{% endblock %}

myapp/templates/faq_list.html
<!-- myapp/templates/myapp/faq_list.html -->
<!DOCTYPE html>
<html>
<head>
    <title>FAQ List</title>
</head>
<body>
    <h1>Frequently Asked Questions</h1>
    <ul>
        {% for faq in faqs %}
            <li>
                <strong>{{ faq.question }}</strong><br>
                {{ faq.answer }}
            </li>
        {% endfor %}
    </ul>
</body>
</html>

myapp/templates/index.html
{% extends 'base.html' %}

{% block content %}
  <style>
    .card-hover:hover {
      transform: scale(1.05);
      transition: transform 0.3s ease-in-out;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      border: 5px solid #343a40; /* Add your desired dark border color */
    }

    /* Additional style for the circular images */
    .circle-img {
      border-radius: 50%;
      width: 50px; /* Adjust as needed */
      height: 50px; /* Adjust as needed */
      margin-right: 10px; /* Adjust spacing */
    }

    /* Adjust card and grid sizes */
    .card-deck {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
      grid-gap: 20px;
      justify-content: space-around;
    }

    .card {
      width: 100%;
      margin: 0;
    }

    .card-img-top {
      object-fit: cover;
      height: 150px;
    }
  </style>

  <body>
    <div class="container">
  
      <!-- Card Deck -->
      <div class="card-deck mt-4">
        {% for i in p %}
          <div class="card mb-4 card-hover">
            <a href="{% url 'myapp:detail' i.id i.slug %}">
              <img src="{{i.img.url}}" class="card-img-top" alt="{{i.title}}">
            </a>
            
            <div class="card-body">
              <h5 class="card-title">
                <a href="{% url 'myapp:detail' i.id i.slug %}">{{i.title}}</a>
              </h5>
              {% if i.product_avaliable %}
                <p class="card-text text-success">₹{{i.price}}</p>
              {% else %}
                <p class="card-text text-danger">Out of Stock</p>
              {% endif %}
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </body>
{% endblock %}

myapp/templates/order.html
{% extends 'base.html' %}
{% block content %}
<b>Cart:</b><br>
{% for i in items %}
{{i.product}}<br>
{% endfor %}
pay:{{total}}
<h1>Show me the money!</h1>
<!-- writes out the form tag automatically -->
{{ form.render }}
{% endblock %}

myapp/templates/otp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST" action="{% url 'myapp:otp' otp=otp username=username password=password email=email %}">
    {% csrf_token %}
    <h1>Enter OTP:</h1>
    <input type="text">
    <button>submit</button>
    </form>
</body>
</html>

myapp/templates/wishlist.html
<!-- myapp/templates/wishlist.html -->

{% extends 'base.html' %}

{% block content %}
  <div class="container mt-4">
    <h2>My Wishlist</h2>
    {% if wishlist.products.all %}
      <div class="row">
        {% for product in wishlist.products.all %}
          <div class="col-md-4 mb-4">
            <div class="card">
              <img src="{{ product.img.url }}" class="card-img-top" alt="{{ product.title }}">
              <div class="card-body">
                <h5 class="card-title">{{ product.title }}</h5>
                <p class="card-text">{{ product.description }}</p>
                <p class="card-text">Price: ${{ product.price }}</p>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    {% else %}
      <p>Your wishlist is empty.</p>
    {% endif %}
  </div>
{% endblock %}